### ISSUE TITLE
Some Resource LIstings do not show

### ISSUE THREAD

**Issue by kinlane** [postmanlabs/covid-19-apis#278] opened 2020-05-08 03:01 UTC
Some listings aren't showing on the main page -- what is restricting them?

https://twitter.com/kinlane/status/1258592319575478274

**Comment by ch264** [comment] 2020-05-11 17:19
@arlemi The above mentioned listing is showing on https://covid-19-apis.postman-beta.com/. This means that the listing has been merged to develop branch. 
In order for the listing to show on the production site: https://covid-19-apis.postman.com/, a PR from develop to master has to be created and approved. 

Here it is: https://github.com/postmanlabs/covid-19-apis/pull/281

Showing updates first on a beta site is a checkpoint that everything renders as anticipated and not a bug. A therefore removed the label. Please fell free to merge the PR once approved.

**Closed by ch264** 2020-05-11 17:19 UTC
